### ISSUE TITLE
Missing  Graft to local dotted lines in Graph View

### ISSUE THREAD

**Issue by pasqualedante** [mikejpeters/hgweb-boundstate-theme#7]
As show in attached screenshot, when I use graft to local, the theme don't show the appropriate dotted lines as in thg.
![bug-in-action](https://cloud.githubusercontent.com/assets/813690/6105248/5a2d5730-b055-11e4-9e4c-47fcf8c28e88.png)

**Comment by mikejpeters** [comment]
Hi @pasqualedante, can you provide me a link to a public repo that has a graph like this for testing (involving a graft to local)? I am not an avid mercurial user anymore so I'm not familiar with how to do this.

Also do you know if the lines are correctly drawn by other mercurial themes? If it is a limitation of hweb I will probably not be able to fix it.

**Comment by pasqualedante** [comment]
Hi @mikejpeters , you are right: I have verified that hgweb behaves the same. My ticket is invalid and can be closed.
