### ISSUE TITLE
Missing references for tags and bookmarks.

### ISSUE THREAD

**Issue by MilesParker** [mikejpeters/hgweb-boundstate-theme#9]
I'm wondering if maybe there is an assumption that boundstate is making about how I have my hgweb configured, but it can't seem to find my tags, branches or bookmarks. Note in screenshot below that they aren't substituted. Also, if I click on Branches or Tags I get "Loading.." but nothing happens.

![boundstateissue](https://cloud.githubusercontent.com/assets/361614/7396825/1611a1cc-ee59-11e4-9dd5-e15c5c03b9f0.png)

**Comment by MilesParker** [comment]
Sorry, meant to mention that nothing shows up in the graph view either. I wonder if the issue might be that I'm only serving one repository..?

**Comment by MilesParker** [comment]
Ok, figured it out. For others who might run into this, my Ubuntu mercurial version was wildly out of date. (1.4.x) That wasn't obvious because ubuntu default setup isn't retrieving the latest version. I forced an update and everything is working great!

**Comment by mikejpeters** [comment]
Thanks for the info.  I'll update the readme when I have some time.
